name: "Publish new release"

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        id: gradlew-build
        run: chmod +x gradlew && ./gradlew clean build
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ steps.gradlew-build.outputs.MINECRAFT_VERSION }}
          separator: .
      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: build/libs/sort_savvy-${{ steps.gradlew-build.outputs.MOD_VERSION }}.jar
          game_endpoint: minecraft
          relations: fabric-api:requiredDependency,fabric-language-kotlin:requiredDependency,owo-lib:requiredDependency
          game_versions: Minecraft ${{ steps.split.outputs._0 }}.${{ steps.split.outputs._1 }}:${{ steps.gradlew-build.outputs.MINECRAFT_VERSION }},Java ${{ steps.gradlew-build.outputs.JAVA_VERSION }},Fabric
          project_id: 852994
          token: ${{ secrets.CF_API_TOKEN }}
