name: "Publish new release"

on:
  release:
    types:
      - created

env:
  VERSIONS: Minecraft 1.19:1.19.2,Java 17,Fabric
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{env.JAVA_VERSION}}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        id: gradlew-build
        run: chmod +x gradlew && ./gradlew clean build
      - name: Get color
        run: echo "Version is ${{ steps.gradlew-build.outputs.version }}"
      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: build/libs/sort_savvy-${{ steps.gradlew-build.outputs.version }}.jar
          game_endpoint: minecraft
          relations: fabric-api:requiredDependency
          game_versions: ${{env.VERSIONS}}
          project_id: 852994
          token: ${{ secrets.CF_API_TOKEN }}
