name: "Publish new release"

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew clean build
      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: build/libs/sort_savvy-${{ steps.build.outputs.version }}.jar
          game_endpoint: minecraft
          relations: fabric-api:requiredDependency
          game_versions: Minecraft 1.19:1.19.2,Java 17,Fabric
          project_id: 852994
          token: ${{ secrets.CF_API_TOKEN }}
